### ISSUE TITLE
Custom crosshair stays on all the time

### ISSUE THREAD

**Issue by Sizzler48** [Kruphixx/producthud#10]
Other custom HUD's have it set up so that the HUD crosshair goes away on death or spectating.

I can see what the file was updated to draw the crosshair to HudPlayerClas.res, which should let the HUD crosshair disappear on death, but it seems to stay.

**Comment by Sizzler48** [comment]
![image](https://github.com/user-attachments/assets/14aced7a-7a0e-4864-a176-d308a811ea3f)

**Comment by Kruphixx** [comment]
Not a bug, the #base for the crosshair is actually in hudlayout, not hudplayerclass. I don't think it was ever in hudplayerclass.
