### ISSUE TITLE
The problem with HUD

### ISSUE THREAD

**Issue by Saint-Son** [Kruphixx/producthud#11]
![20241230133405_1](https://github.com/user-attachments/assets/9d6209bb-af82-4286-aef8-92ca91951f42)
![20241230133409_1](https://github.com/user-attachments/assets/ddde5695-5921-43ca-a5dd-81260c7ee694)

in my opinion, everything is clear here.

**Comment by Kruphixx** [comment]
Fixed in https://github.com/Kruphixx/producthud/commit/e75b804770a729cfdac7d4339d89fe15fe70604b, thank you.

![Screenshot 2024-12-30 131155](https://github.com/user-attachments/assets/339b0015-6ee6-48a7-8b46-e6d2a986f1b7)
