### ISSUE TITLE
a small request for hud customization

### ISSUE THREAD

**Issue by Saint-Son** [Kruphixx/producthud#12]
![imagesdf](https://github.com/user-attachments/assets/0b4be52f-902e-406f-b061-95adefe58481)
can you please tell me how to remove the damage counter on health?

**Comment by Kruphixx** [comment]
Go to resource/ui/huddamageaccount_base.res and set the "wide" and "tall values for DamageAccountValue and DamageAccountValueShadow to 0. This should disable it.

**Comment by Saint-Son** [comment]
Yeah, it's working. thanks
