### ISSUE TITLE
Missing text wrapping

### ISSUE THREAD

**Issue by gatesbydude** [Kruphixx/producthud#3]
![image](https://github.com/Kruphixx/producthud/assets/91558690/a61eb1f1-0d00-47b5-949c-daf7414b4d5a)

**Comment by Kruphixx** [comment]
Should be fixed in https://github.com/Kruphixx/producthud/commit/26e015559e189469667bb94da776d24e23df79b3. I don't really have a way to test this so let me know how it goes.
