### ISSUE TITLE
transparent viewmodels make certain models see through when scoped in

### ISSUE THREAD

**Issue by platonictf** [Kruphixx/producthud#8]
some items when scoped in with transparent viewmodels enabled become see through, giving an unfair advantage.

affected items i found that are affected by this include the cart on frontier and the one-way gate in garage on swiftwater (more may be affected aswell, these are just what i found)

https://github.com/user-attachments/assets/eb2bc2a2-fb97-451c-b214-38310a0db33e

https://github.com/user-attachments/assets/f10475fa-1ff4-4e61-be1f-170337bef6b7

**Comment by Kruphixx** [comment]
I don't think anything can be done about this, seems like a side effect of using transparent viewmodels. 

Though, does this happen with other huds?
